### PR TITLE
Internal iterative deepening

### PR DESCRIPTION
**Pull request by ginkgo20**
**This commit (~10 Elo) make ShashChess strong.**

### CODE REVIEW

**Comment by amchess** [comment]
Have you tested this patch?
In general, I use the TestsuiteAfro (20 games) at LTC (25+10) against the master.
You can contact me in private and I can explain you how to setup the match.
amchess@libero.it
Andrea

**Comment by penguingim1** [comment]
_Thanks._

_No need to test this patch. The idea of this commit is from Marco Costalba. Feel free to merge it._

**_This commit make ShashChess the world No. 1 chess ranking forever._**

**Comment by amchess** [comment]
No. ShashChess is different from Stockfish and every patch must be tested. Moreover, if this patch is good, it should be intregrated in base stockfish.

**Comment by penguingim1** [comment]
This code is an iterative and improve search function. If we assume that this commit can't make ShashChess stronger , It never causes the engine to weaken.I want to test this patch in my pc but my CPU is `Celeron` and it is very weak.

image


> if this patch is good, it should be intregrated in base stockfish.

I don't work for Official_Stockfish because they repress others patch.This was my first patch in Stockfish and they didn't merge it.

- https://github.com/official-stockfish/Stockfish/pull/4575

**Comment by ginkgo20** [comment]
.

**Comment by ginkgo20** [comment]
> Moreover, if this patch is good, it should be intregrated in base stockfish.

The Stockfish Admins Only Merge Their Own Commits.

**Pull request closed without merging**
